<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Team_model extends CI_Model {
    function __construct() {
        parent::__construct();
		    $this->load->database();
    }
    function team_fetch_data(){				      $user_type = $this->session->userdata('user_type');		$user_id = $this->session->userdata('user_id');		$org_id = $this->session->userdata('org_id');							$this->db->select("*");   					  if($user_type==0){						$this->db->where("org_id", $user_id ); 											  }elseif($user_type==3){ 					  $this->db->where("org_id", $org_id);					   					  }else{						  					  }            $this->db->from("team");             $query = $this->db->get();             return $query;  			}	 function delete_data($id){             $this->db->where("id", $id);             $this->db->delete("team");                   }  	  	  	  function getAllteams(){        							$user_type = $this->session->userdata('user_type');		$user_id = $this->session->userdata('user_id');		$org_id = $this->session->userdata('org_id');							   					  if($user_type==0){												$query = $this->db->query('SELECT team FROM team where org_id="'.$user_id.'"');						 return $query->result();					  }elseif($user_type==3){ 					  					   $query = $this->db->query('SELECT team FROM team where org_id="'.$org_id.'"');					    return $query->result();					  }else{						$query = $this->db->query('SELECT team FROM team');  						 return $query->result();					  } 		                    }	  function getAllemployees(){          						$user_type = $this->session->userdata('user_type');		$user_id = $this->session->userdata('user_id');		$org_id = $this->session->userdata('org_id');							   					  if($user_type==0){												$query = $this->db->query('SELECT id,name FROM organization where org_id="'.$user_id.'"');						 return $query->result();					  }elseif($user_type==3){ 					  					   $query = $this->db->query('SELECT id,name FROM organization where org_id="'.$org_id.'"');					    return $query->result();					  }else{						$query = $this->db->query('SELECT id,name FROM organization');  						 return $query->result();					  }          							  }            
       function getAllorganization(){          $query = $this->db->query('SELECT id,name FROM organization where login_type=0');        return $query->result();                    }												function fetch_single_data($user_id)        {             $this->db->where("id", $user_id);             $query = $this->db->get("team");             return $query;                   }  	}

